### PR TITLE
Keyring base API

### PR DESCRIPTION
**Pull request by MeghaShetty**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mattsb42-aws** [comment]
I'm not sure why this showing all the files added in #158 as new, but would you please rebase on top of `aws/keyring`? This is pulling in more changes than should be here.

File: src/aws_encryption_sdk/keyring/base.py [hunk 1]
```diff
@@ -0,0 +1,42 @@
...
+# ANY KIND, either express or implied. See the License for the specific
+# language governing permissions and limitations under the License.
+"""Base class interface for Keyrings."""
+
+
+class Keyring(object):
+    """Parent interface for Keyring classes."""
+
+    def on_encrypt(self, encryption_materials):
+        """Generates a data key and encrypts it using all wrapping keys the Keyring is associated with.
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]: Looks like I still have this pylint check disabled, but please make all docstring descriptions in imperative mood.

ex:
```suggestion
        """Generate a data key if not present and encrypt it using any available wrapping keys.
```

File: src/aws_encryption_sdk/keyring/base.py [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+        :type : aws_encryption_sdk.materials_managers.EncryptionMaterials
+        :returns encryption_materials: Contains signing key, unencrypted data key, encrypted data keys,
+                                    encryption context and algorithm suite required to encrypt data key
+        :rtype : aws_encryption_sdk.materials_managers.EncryptionMaterials
+        :raises AttributeError: if encryption materials not available
+        """
+        raise NotImplementedError("Keyring does not implement on_encrypt function")
+
+    def on_decrypt(self, decryption_materials):
+        """Tries to decrypt one of the keys in the list of encrypted data keys using wrapping keys
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]: I think we can simplify this to just "Attempt to decrypt the encrypted data keys."

File: src/aws_encryption_sdk/keyring/base.py (hunk 1 above)
Comment (MeghaShetty) [reply src/aws_encryption_sdk/keyring/base.py]: I will do that

File: src/aws_encryption_sdk/keyring/base.py (hunk 2 above)
Comment (MeghaShetty) [reply src/aws_encryption_sdk/keyring/base.py]: Changed it

File: src/aws_encryption_sdk/keyring/base.py [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+
+class Keyring(object):
+    """Parent interface for Keyring classes."""
+
+    def on_encrypt(self, encryption_materials):
+        """Generate a data key if not present and encrypt it using any available wrapping key.
+
+        :param encryption_materials: Contains signing key, encryption context and algorithm suite
+                                    required to encrypt data key
+        :type : aws_encryption_sdk.materials_managers.EncryptionMaterials
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]:
```suggestion
        :type encryption_materials: aws_encryption_sdk.materials_managers.EncryptionMaterials
```

File: src/aws_encryption_sdk/keyring/base.py [hunk 4]
```diff
@@ -0,0 +1,41 @@
...
+        :returns encryption_materials: Contains signing key, unencrypted data key, encrypted data keys,
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]:
```suggestion
        :returns: Contains signing key, unencrypted data key, encrypted data keys,
```

File: src/aws_encryption_sdk/keyring/base.py [hunk 5]
```diff
@@ -0,0 +1,41 @@
...
+        :rtype : aws_encryption_sdk.materials_managers.EncryptionMaterials
+        :raises AttributeError: if encryption materials not available
+        """
+        raise NotImplementedError("Keyring does not implement on_encrypt function")
+
+    def on_decrypt(self, decryption_materials):
+        """Attempt to decrypt the encrypted data keys.
+
+        :param decryption_materials: Contains verification key, list of encrypted data keys.
+        :type : aws_encryption_sdk.materials_managers.DecryptionMaterials
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]:
```suggestion
        :type decryption_materials: aws_encryption_sdk.materials_managers.DecryptionMaterials
```

File: src/aws_encryption_sdk/keyring/base.py [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+        :returns decryption_materials: Contains verification key, list of encrypted data keys and decrypted data key.
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]:
```suggestion
        :returns: Contains verification key, list of encrypted data keys and decrypted data key.
```

File: src/aws_encryption_sdk/keyring/base.py [hunk 7]
```diff
@@ -0,0 +1,41 @@
...
+    def on_encrypt(self, encryption_materials):
+        """Generate a data key if not present and encrypt it using any available wrapping key.
+
+        :param encryption_materials: Contains signing key, encryption context and algorithm suite
+                                    required to encrypt data key
+        :type : aws_encryption_sdk.materials_managers.EncryptionMaterials
+        :returns encryption_materials: Contains signing key, unencrypted data key, encrypted data keys,
+                                    encryption context and algorithm suite required to encrypt data key
+        :rtype : aws_encryption_sdk.materials_managers.EncryptionMaterials
+        :raises AttributeError: if encryption materials not available
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]:
```suggestion
        :raises NotImplementedError: if method is not implemented
```

File: src/aws_encryption_sdk/keyring/base.py [hunk 8]
```diff
@@ -0,0 +1,41 @@
...
+        raise NotImplementedError("Keyring does not implement on_encrypt function")
+
+    def on_decrypt(self, decryption_materials):
+        """Attempt to decrypt the encrypted data keys.
+
+        :param decryption_materials: Contains verification key, list of encrypted data keys.
+        :type : aws_encryption_sdk.materials_managers.DecryptionMaterials
+        :returns decryption_materials: Contains verification key, list of encrypted data keys and decrypted data key.
+        :rtype : aws_encryption_sdk.materials_managers.DecryptionMaterials
+        :raises AttributeError: if decryption materials not available
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]:
```suggestion
        :raises NotImplementedError: if method is not implemented
```

File: src/aws_encryption_sdk/keyring/base.py [hunk 9]
```diff
@@ -0,0 +1,41 @@
...
+#
+# or in the "license" file accompanying this file. This file is
+# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
+# ANY KIND, either express or implied. See the License for the specific
+# language governing permissions and limitations under the License.
+"""Base class interface for Keyrings."""
+
+
+class Keyring(object):
+    """Parent interface for Keyring classes."""
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]: One last thing because I forgot about this until now..
```suggestion
    """Parent interface for Keyring classes.
    
        .. versionadded:: 1.5.0
    """
```

File: src/aws_encryption_sdk/keyring/base.py [hunk 10]
```diff
@@ -0,0 +1,44 @@
...
+                                    required to encrypt data key
+        :type encryption_materials: aws_encryption_sdk.materials_managers.EncryptionMaterials
+        :returns: Contains signing key, unencrypted data key, encrypted data keys,
+                                    encryption context and algorithm suite required to encrypt data key
+        :rtype: aws_encryption_sdk.materials_managers.EncryptionMaterials
+        :raises NotImplementedError: if method is not implemented
+        """
+        raise NotImplementedError("Keyring does not implement on_encrypt function")
+
+    def on_decrypt(self, decryption_materials):
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]: As we discussed offline, per discussion in #163 we need to change this interface. `encrypted_data_keys` should be an iterable of `EncryptedDataKey`.

```suggestion
    def on_decrypt(self, decryption_materials, encrypted_data_keys):
```

File: src/aws_encryption_sdk/keyring/base.py [hunk 11]
```diff
@@ -0,0 +1,47 @@
...
+        """
+        raise NotImplementedError("Keyring does not implement on_encrypt function")
+
+    def on_decrypt(self, decryption_materials, encrypted_data_keys):
+        """Attempt to decrypt the encrypted data keys.
+
+        :param decryption_materials: May contain verification key, algorithm, encryption context and keyring trace.
+        :type decryption_materials: aws_encryption_sdk.materials_managers.DecryptionMaterials
+        :param encrypted_data_keys: List of encrypted data keys.
+        :type: Iterable of `aws_encryption_sdk.structures.EncryptedDataKey`
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]:
```suggestion
        :type: Iterable of :class:`aws_encryption_sdk.structures.EncryptedDataKey`
```

File: src/aws_encryption_sdk/keyring/base.py [hunk 12]
```diff
@@ -0,0 +1,47 @@
...
+                                    encryption context and algorithm suite required to encrypt data key
+        :rtype: aws_encryption_sdk.materials_managers.EncryptionMaterials
+        :raises NotImplementedError: if method is not implemented
+        """
+        raise NotImplementedError("Keyring does not implement on_encrypt function")
+
+    def on_decrypt(self, decryption_materials, encrypted_data_keys):
+        """Attempt to decrypt the encrypted data keys.
+
+        :param decryption_materials: May contain verification key, algorithm, encryption context and keyring trace.
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]: Let's be consistent with the encryption materials.

I'm inclined to say that we should punt any description of the contents of encryption/decryption materials to the definitions of those structures (which Sphinx will link to when the docs are generated). Maybe just say "encryption/decryption materials for the keyring to modify" and "optionally modified encryption/decryption materials"?

File: src/aws_encryption_sdk/keyring/base.py [hunk 13]
```diff
@@ -0,0 +1,47 @@
...
+"""Base class interface for Keyrings."""
+
+
+class Keyring(object):
+    """Parent interface for Keyring classes.
+
+    .. versionadded:: 1.5.0
+    """
+
+    def on_encrypt(self, encryption_materials):
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]: Add type hints.

```suggestion
    def on_encrypt(self, encryption_materials):
    # type: (EncryptionMaterials) -> EncryptionMaterials
```

File: src/aws_encryption_sdk/keyring/base.py [hunk 14]
```diff
@@ -0,0 +1,47 @@
...
+# may not use this file except in compliance with the License. A copy of
+# the License is located at
+#
+# http://aws.amazon.com/apache2.0/
+#
+# or in the "license" file accompanying this file. This file is
+# distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF
+# ANY KIND, either express or implied. See the License for the specific
+# language governing permissions and limitations under the License.
+"""Base class interface for Keyrings."""
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]: Add imports for type hints (see later comments).

```suggestion
"""Base class interface for Keyrings."""
from aws_encryption_sdk.material_managers import DecryptionMaterials, EncryptionMaterials
from aws_encryption_sdk.structures import EncryptedDataKey

try:  # Python 3.5.0 and 3.5.1 have incompatible typing modules
    from typing import Iterable  # noqa pylint: disable=unused-import
except ImportError:  # pragma: no cover
    # We only actually need these imports when running the mypy checks
    pass
```

File: src/aws_encryption_sdk/keyring/base.py [hunk 15]
```diff
@@ -0,0 +1,47 @@
...
+                                    required to encrypt data key
+        :type encryption_materials: aws_encryption_sdk.materials_managers.EncryptionMaterials
+        :returns: Encryption materials containing signing key, unencrypted data key, encrypted data keys,
+                                    encryption context and algorithm suite required to encrypt data key
+        :rtype: aws_encryption_sdk.materials_managers.EncryptionMaterials
+        :raises NotImplementedError: if method is not implemented
+        """
+        raise NotImplementedError("Keyring does not implement on_encrypt function")
+
+    def on_decrypt(self, decryption_materials, encrypted_data_keys):
```
Comment (mattsb42-aws) [inline src/aws_encryption_sdk/keyring/base.py]: Add type hints.

```suggestion
    def on_decrypt(self, decryption_materials, encrypted_data_keys):
    # type: (DecryptionMaterials, Iterable[EncryptedDataKey]) -> DecryptionMaterials
```

**Comment by mattsb42-aws** [comment]
We still need tests for this, but this is simple enough that I'm ok leaving that for another PR since this is not going into `master` yet anyway. I broke this out in #146 to make sure we don't forget.
